version: '3'
services:
  tg-discount-service:
    ports:
      - 8082:8080
    image: evgeniypnf/tg-discount-service:latest

  discount-service:
    depends_on:
      - db
    image: evgeniypnf/discount-service:latest
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/discount-service
      DATABASE_USERNAME: User
      DATABASE_PASSWORD: 123
    ports:
      - 8081:8080

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: User
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: discount-service

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M
    links:
      - zookeeper

