apiVersion: v1
kind: Service
metadata:
  name: pg-database
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pg-database
subsets:
  - addresses:
      - ip: 192.168.99.1
    ports:
      - name: 5432-5432
        port: 5432
        protocol: TCP