apiVersion: v1 # Kubernetes API version
kind: Service  # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: discount-service
  labels:
    tier: backend
spec:
  selector:
    app: discount-service
    tier: backend
  ports:
    - protocol: TCP
      port: 80 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-service
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount-service
  template:
    metadata:
      labels:
        app: discount-service
        tier: backend
    spec:
      containers:
        - name: discount-service
          image: evgeniypnf/discount-service
          ports:
            - containerPort: 8080  # The port that the container is running on in the cluster
          env:
            - name: host
              valueFrom:
                configMapKeyRef:
                  name: discount-config
                  key: host
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: discount-secret
                  key: url
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: discount-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: discount-secret
                  key: password
            - name: client_id
              valueFrom:
                secretKeyRef:
                  name: discount-secret
                  key: client_id
            - name: client_secret
              valueFrom:
                secretKeyRef:
                  name: discount-secret
                  key: client_secret