apiVersion: v1 # Kubernetes API version
kind: Service  # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: discount-service
  labels:
    tier: backend
spec:
  selector:
    app: discount-service
    tier: backend
  ports:
    - protocol: TCP
      port: 8081 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-service
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount-service
  template:
    metadata:
      labels:
        app: discount-service
        tier: backend
    spec:
      containers:
        - name: discount-service
          image: evgeniypnf/discount-service
          ports:
            - containerPort: 8080  # The port that the container is running on in the cluster